CREATE TABLE ProjectDetail (
	id INT NOT NULL PRIMARY KEY,
    projectName VARCHAR(45) NOT NULL
);


CREATE TABLE ARTICLE (

	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(45) NOT NULL,
	PEREX VARCHAR(80) NOT NULL,db
	PUBLISHED_DATE DATETIME NOT NULL,
	ISVISIBLE BOOLEAN
);


CREATE TABLE USER (

  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  LOGIN VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL
);
